[project]
name = "fmai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Coen Büller", email = "coen.buller@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "moviepy>=2.0.0",
    "torch>=2.14.0",
    "tqdm>=4.70.1",
    "vmas>=1.5.2",
]

[project.scripts]
fmai = "fmai:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
