[project]
name = "fmai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Coen Büller", email = "coen.buller@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.11.2",
    "moviepy>=2.0.0",
    "tensordict>=0.14.2",
    "torch>=2.14.0",
    "torchrl>=0.14.0",
    "tqdm>=4.70.1",
    "vmas>=1.5.2",
    "qsfo @ git+https://github.com/CoenBuller/artifact-fm-qsfo.git@main",
]

[project.scripts]
fmai = "fmai:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[[tool.uv.index]]
name = "pytorch-cu126"
url = "https://download.pytorch.org/whl/cu126"
explicit = true

[tool.uv.sources]
torch = [{ index = "pytorch-cu126", marker = "sys_platform == 'win32'" }]
